name: deploy

on: 
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: executing remote ssh commands using secret key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/telegram_bots/GameCheckersBot/
          yarn daemon:stop
          git fetch --all && git reset --hard origin/master
          yarn daemon:run
